/**
 *Clase: Cliente
 *
 *@version: 0.1
 *
 *Fecha de Creación: 30/04/2020
 *
 *Fecha de Modificación:
 *
 *@autor: Yanvier
 *
 *Copyright: CECAR
 *
 */
package edu.cecar.vista;

import edu.cecar.componentesReutilizables.SocketObjeto;

import edu.cecar.modelo.Documento;

import java.io.FileOutputStream;

import java.util.List;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

/**
 * Clase que contiene la vista del cliente
 * 
 */
public class Cliente extends javax.swing.JFrame {

    private SocketObjeto socketObjeto;

    /**
     * Creates new form Cliente
     */
    public Cliente() {
        initComponents();
        socketObjeto = new SocketObjeto("127.0.0.1", 7000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btIniciar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbContenido = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cliente SAS");
        setResizable(false);

        btIniciar.setText("Iniciar");
        btIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIniciarActionPerformed(evt);
            }
        });

        jtbContenido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name of the Sport Events", "Name of the Winners"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtbContenido);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(411, 411, 411)
                .addComponent(btIniciar)
                .addContainerGap(411, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btIniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void llenarTabla(Object object)	{
        Documento documento = (Documento) object;
        List<String> ladoIzq = documento.getCellsLeft();
        List<String> ladoDer = documento.getCellsRight();
        
        int listLength = ladoIzq.size();
        
        String matriz[][] = new String[listLength][2];
        for (int i = 0; i < ladoIzq.size(); i++) {
            matriz[i][0] = ladoIzq.get(i);
            matriz[i][1] = ladoDer.get(i);
            

        }
        jtbContenido.setModel(new DefaultTableModel(
                matriz, new String[]{
                    "Name of the Sports Events", "Name of the Winners"
                }
        ));
        
    }
    private void crearArchivoDescargado(Object object) throws Exception {

        Documento documento = (Documento) object;

        FileOutputStream fileOutputStream = new FileOutputStream("archivosCliente\\"
                + documento.getNombreArchivo());

        fileOutputStream.write(documento.getBytesArchivo());

        fileOutputStream.close();

    }

    private void btIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIniciarActionPerformed
        try {
            Documento documento = new Documento("DatosDeportivos.doc");
            socketObjeto.getSalida().writeObject(documento);

            Object object = socketObjeto.getEntrada().readObject();
            crearArchivoDescargado(object);
            llenarTabla(object);
            JOptionPane.showMessageDialog(this, "Proceso Terminado");
        } catch (Exception ex) {
           
        }
    }//GEN-LAST:event_btIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btIniciar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbContenido;
    // End of variables declaration//GEN-END:variables
}
